#! /bin/bash

gulp build
mkdir -p _site
cd _site
git init
git remote add origin git@github.com:amonks/saturn.git
git pull origin gh-pages
git checkout gh-pages
rm -rf ./*
cp ../dist/* ./
git add --all .
git commit -am 'update gh-pages'
git push --force
cd ..
rm -rf _site
